# Generated by Django 4.1.2 on 2022-12-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('setting_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('arithmetic', models.CharField(max_length=250, verbose_name='Arithmetic')),
                ('difficulty', models.CharField(max_length=250, verbose_name='Difficulty')),
                ('speed', models.CharField(max_length=250, verbose_name='Speed')),
                ('lvl', models.CharField(max_length=250, verbose_name='lvl')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assessment.player', verbose_name='Player')),
            ],
        ),
    ]
